### ISSUE TITLE
Add a section in the flavored pubspec files to remove any key.

### ISSUE THREAD

**Issue by kushalmahapatro** [kushalmahapatro/pubspec_manager#36]
This section can be a miny version of the pubspec content. 

```
remove:
  homepage:
  
  dependencies:
    args: ^2.4.2
  
  dev_dependencies:
    lints: ^2.1.1
  
  dependency_overrides:
    args: ^2.4.2
```
